frontend:
  image: ghcr.io/archit0k/taskboard-frontend
backend:
  image: ghcr.io/archit0k/taskboard-backend
replicaCount: 2
ingress:
  enabled: true
  host: taskboard.example.com
hpa:
  enabled: true
